version: '3'
services:
  postgres:
    image:
      "postgres:12.0-alpine"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_USER: ${POSTGRES_USER-user}
      POSTGRES_DB: ${POSTGRES_DB-photos}

  django:
    build: .
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; python /code/manage.py migrate --noinput && python /code/manage.py collectstatic --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - media:/code/media
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres-data:
  media: